### ISSUE TITLE
paper citations

### ISSUE THREAD

**Issue by cmaimone** [chainsawriot/sweater#15]
Looks like the paper cites the R word2vec package, but not the original dataset.  Should original dataset be cited?  Same for small_reddit, glove_math?

Perhaps list them in the paper as sample word embeddings that are included in the package?

re: https://github.com/openjournals/joss-reviews/issues/4036

**Comment by chainsawriot** [comment]
If you are talking about the paper, I've cited both @mikolov2013distributed (the googlenews word2vec embeddings) and @pennington:2014:G (the GloVE embeddings). The `small_reddit` is not used.

But I can in the paper list out all the sample (but abridged) word embeddings provided in the package.
