### ISSUE TITLE
paper: other R packages?

### ISSUE THREAD

**Issue by cmaimone** [chainsawriot/sweater#16]
Are there any other R packages available for bias in word embeddings, or more generally for bias in text corpora?  If not, you can state that.  If there are, would be good to reference.  

The statement that sweater brings together methods that were only reported in papers' supplemental materials is clear -- I get the utility of the package.  I just don't know if there's anything else out there or not.  

re: https://github.com/openjournals/joss-reviews/issues/4036

**Comment by chainsawriot** [comment]
@cmaimone As far as I know, there is only one R package available aimed at replicating the analysis in Caliskan et al. (https://github.com/conjugateprior/cbn , i.e. only `weat`) Other than that, I don't think there are R packages providing other methods.

The Python package [wefe](https://github.com/dccuchile/wefe) is kind of similar to this package.

I can mention these in the paper.
