### ISSUE TITLE
documentation: what is the preferred workflow?

### ISSUE THREAD

**Issue by cmaimone** [chainsawriot/sweater#19]
> It is recommended to use the function query() to make a query and calculate_es() to calculate the effect size. You can also use the functions listed below.

I'm confused why there are both general functions and specific ones -- seems like you should either specify the method as an argument to query() or have to use a query function specific to each method -- not both options.  

Are functions mac(), rnd(), nas() etc functions that create a query?  If so, it would be great to get "query" in their names to make that clear.

re: https://github.com/openjournals/joss-reviews/issues/4036

**Comment by chainsawriot** [comment]
@cmaimone As of now, the preferred workflow is certainly `query`. The monolithic `query` interface is unfortunately an afterthought (4c0751c2b235265e807cf87e0cb813a170c914d0) and the package started with individual functions for each method. I know that there has been legacy code in some other researchers' analytic scripts using those individual functions. For backward compatibility, I need to keep those functions — their names at least — as they were (also, it's too late now to rename those functions with some tidyverse-style verb-based function names, similar to your "get `query` in their names").

Maybe a more proper approach is to make those individual functions less prominent in the README and state that they are here for backward compatibility.

**Comment by cmaimone** [comment]
Downplaying them in the readme seems like a good strategy -- maybe even mark them as depreciated and plan to take them out in the future (or, if you prefer separate functions, change the names)?  Your package is pretty young to feel like you're locked in forever, but I do appreciate the care for existing users.

**Comment by chainsawriot** [comment]
TODO

- [x] downplay those functions in the README
- [x] improve documentation regarding the relationship between `query` and those functions
