### ISSUE TITLE
documentation: first example

### ISSUE THREAD

**Issue by cmaimone** [chainsawriot/sweater#20]
The first example uses googlenews without introducing it first -- not even that it has word embeddings in it.  

Output from the first example isn't explained.  I found it confusing.  

```
#> Effect size:  0.1375856
#> 
#> ── Functions ─────────────────────────────────
#> • <calculate_es()>: Calculate effect size
#> • <plot()>: Plot the bias of each individual word
```

Why are the function names in <>?  Why are these listed?  Are these next steps that I should take?  Do I supply the output of the query function to them?

What is mac_neg$P?

re: https://github.com/openjournals/joss-reviews/issues/4036

**Comment by chainsawriot** [comment]
@cmaimone I have rewritten the first example and it is now clearer (I think). Concerning the angle brackets, it is a bit confusing. I just found that the latest version of `cli` has a new style called `.fun` specifically for printing functions (at least that's how the RStudio team suggested).

I see some packages are using `.fun` now, e.g. `crossjoin` here.

![image](https://user-images.githubusercontent.com/637269/151660249-35ad6e22-e6b5-48dd-bbdc-8826bb887f81.png)

 I hope it is better now, although it still has a pair of surrounding backticks.

``` r
require(sweater)
#> Loading required package: sweater
S4 <- c("math", "algebra", "geometry", "calculus", "equations", "computation", "numbers", "addition")
A4 <- c("male", "man", "boy", "brother", "he", "him", "his", "son")
query(glove_math, S_words = S4, A_words = A4)
#> 
#> ── sweater object ──────────────────────────────────────────────────────────────
#> Test type:  mac 
#> Effect size:  0.09579005
#> 
#> ── Functions ───────────────────────────────────────────────────────────────────
#> • `calculate_es()`: Calculate effect size
#> • `plot()`: Plot the bias of each individual word
```

<sup>Created on 2022-01-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
