### ISSUE TITLE
error printing sweater object

### ISSUE THREAD

**Issue by cmaimone** [chainsawriot/sweater#24]
I ran the first example, and then tried to print the mac_neg object:

```
> mac_neg

── sweater object ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Test type:  mac 
Effect size:  0.1375856 

── Functions ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error in base::nchar(wide_chars$test, type = "width") : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/cli/R/sysdata.rdb' is corrupt
In addition: Warning messages:
1: In base::nchar(wide_chars$test, type = "width") :
  restarting interrupted promise evaluation
2: In base::nchar(wide_chars$test, type = "width") :
  internal error -3 in R_decompress1


> packageVersion("cli")
[1] ‘3.1.1’
```

Not sure if this is just my system?  I had the same issue when trying to print other sweater objects that were the result of running the examples.

**Comment by chainsawriot** [comment]
@cmaimone Thanks for raising this. This is a typical (probably base R) installation issue of some packages (`cli` in this case) that should be resolved by restarting your R session on your Mac. If you are using RStudio, try: `.rs.restartR()`. If it still doesn't work, please try to remove `cli` and install it again: 

```r
remove.packages("cli")
install.packages("cli")
```


Ref: https://stackoverflow.com/questions/67001134/am-not-able-to-load-tidyverse-in-r-4-0-5-any-leads
