### ISSUE TITLE
code structure question

### ISSUE THREAD

**Issue by cmaimone** [chainsawriot/sweater#25]
Are effect sizes expensive to compute?  Looks like a call to query() will compute the effect size automatically and print it out, so my guess is no?  Is there a reason not to store the computed effect size in the sweater objects (so it can be referenced later)?  With the effect size functions, I'd have to store the effect size for a query in a separate variable from the query object, which makes it easy to get things messed up in the code -- would be nice to have it as part of the result object.

Could still have es functions for convenience of accessing that component of the object if you wanted.

re: https://github.com/openjournals/joss-reviews/issues/4036

**Comment by chainsawriot** [comment]
@cmaimone effect sizes are not expensive to compute and for many methods there is only one effect size. But the reason I don't want to put it inside the S3 is that for WEAT there are several ways to calculate ES. It would create the problem of which ES to put inside the S3.

``` r
require(sweater)
#> Loading required package: sweater

S4 <- c("math", "algebra", "geometry", "calculus", "equations", "computation", "numbers", "addition")
T4 <- c("poetry", "art", "dance", "literature", "novel", "symphony", "drama", "sculpture")
A4 <- c("male", "man", "boy", "brother", "he", "him", "his", "son")
B4 <- c("female", "woman", "girl", "sister", "she", "her", "hers", "daughter")
sw <- query(glove_math, S4, T4, A4, B4)

calculate_es(sw)
#> [1] 1.055015
calculate_es(sw, standardize = FALSE)
#> [1] 0.02486533
calculate_es(sw, r = TRUE)
#> [1] 0.4912066
```

<sup>Created on 2022-01-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
