### ISSUE TITLE
Issue of pooled SD in `weat_es()`

### ISSUE THREAD

**Issue by psychbruce** [chainsawriot/sweater#39]
Hi, I'm the author of the [`PsychWordVec`](https://psychbruce.github.io/PsychWordVec/) package (an integrated toolkit of word embedding research). Your `sweater` package inspired me a lot when I developed `test_WEAT()` and `test_RND()` for my package.

Recently I browsed the source code of your `sweater` package and found that you used a different method to compute pooled SD in `weat_es()` if the sample sizes are not balanced (n1 != n2). Particularly, I found this line of code (https://github.com/chainsawriot/sweater/blob/master/R/sweater.R#L87):

`pooled_sd <- sqrt(((n1 -1) * S_var) + ((n2 - 1) * T_var)/(n1 + n2 + 2))`

I'm sure that in statistics this method is usually used to compute the pooled SD (https://www.statisticshowto.com/pooled-standard-deviation/), no matter whether the sample sizes are balanced or not. However, there are two issues to be addressed:

1. For balanced sample sizes (n1 == n2), the pooled SD calculated by this method would be _inconsistent_ with that by Caliskan et al.'s (2017) `sd(c(S_diff, T_diff))` approach. How could we reconcile them? In my `test_WEAT()`, to avoid such inconsistency, I just follow Caliskan et al.'s approach regardless of whether n1 is equal to n2.
2. Indeed, the code of computation is _incorrect_, with a misplaced pair of parentheses `) + (` before `n2 - 1` and a wrong sign in `n1 + n2 + 2` (which should be `n1 + n2 - 2` instead). This could produce substantially wrong results because it actually computes the square root of the sum of `(n1 - 1) * S_var` and `(n2 - 1) * T_var / (n1 + n2 + 2)`. The correct one should be
`pooled_sd <- sqrt(((n1 - 1) * S_var + (n2 - 1) * T_var) / (n1 + n2 - 2))`

Best,
Bruce

**Comment by chainsawriot** [comment]
@psychbruce Thanks for reporting this. I did the following:

1. Made the pooled SD part testable and added the test cases from `effectsize`
2. Fixed the wrong sign you spotted
3. No one knows how the effect size should behave when `S` and `T` are of unequal size. Previously, I had a correspondence with Caliskan and Lowe on why `S` and `T` needed to be of equal size. I can't quote their correspondence here. But I think a stronger disclaimer in the documentation would be better. 

Once again, thanks for reporting this. I wish your package a great success.

**Comment by psychbruce** [comment]
@chainsawriot Thanks. That's great! Let me share my further thoughts on the broader issue of how pooled SD could be calculated in this situation.

### 1. Caliskan's and traditional pooled SDs are essentially different in mathematics

First and basically, according to a formula deduction, these two approches have a systematic difference in the estimate of pooled SD and should better be treated distinctively regardless of the issue of equal or unequal sample sizes.

Define symbols below:
- $SS$ = sum of square
- $M$ = grand mean, $M_1$ = mean of group 1 (`S_words`), $M_2$ = mean of group 2 (`T_words`)
- $N$ = total sample size = $n_1 + n_2$
- $df$ = degree of freedom = $N - 1$ = $n_1 + n_2 - 1$
- $df_1$ = $n_1 - 1$ and $df_2$ = $n_2 - 1$

Then (no matter whether $n_1$ is equal to $n_2$ ):
$$\text{Caliskan's approach: } SD_c = \sqrt{SS \over df}$$
$$\text{Traditional approach: } SD_p = \sqrt{SS_1 + SS_2 \over df_1 + df_2} = \text{(deduction processes omitted...)} = \sqrt{SS - [n_1 \times (M - M_1)^2 + n_2 \times (M - M_2)^2] \over df - 1}$$

And if $n_1 = n_2$ , $M_1 - M = M - M_2$ , then:
$$\text{Traditional approach: } SD_p = \sqrt{SS - \frac{N}{4} (M_1 - M_2)^2 \over df - 1}$$

Therefore, $SD_c$ is usually unequal to (and in most cases larger than) $SD_p$ . Only if $M_1$ is equal or very close to $M_2$ would $SD_c$ be slightly smaller than $SD_p$ . With real data, I have tried several times and did find such differences in practice.

This suggests that Caliskan's approach should provide a more conservative (i.e., smaller) estimate of the effect size, regardless of equal/unequal sample sizes. Moreover, in an extreme situation with only 1 S_word and 1 T_word, Caliskan's approach can still calculate the pooled SD with the two values while the traditional approach cannot (i.e., one value does not have SD).

### 2. Theoretical assumptions differ between these two approaches

Second, my further understanding of these two methods for pooled SD is that they differ in their assumptions.

The traditional approach is undoubtedly often used in psychological and behavioral sciences, where two groups of participants are usually randomly assigned to different treatments. Thus, we assume that the two groups are _heterogeneous_ while their within-group variances are _homogeneous_.

However, for word embeddings research, word similarities may follow the same distribution, and target words (`S_words` and `T_words`) are naturally divided (vs. artificially assigned) into two groups. No experimental manipulation is conducted to the two word groups. So we may assume an overall variance of word similarities or similarity differences. The more data points we include in the calculation of pooled SD, the closer it would be to the population variance. Using a subset of data (i.e., treating n1 and n2 respectively) would usually underestimate the pooled SD and then overestimate the effect size (also as indicated in the first section above with mathematical equations).

Taken together, I understand that Caliskan' approach is more suitable for the calculation of effect sizes in word embeddings research, though not suitable for traditional behavioral experiments. Again, these discussions are not related to the sample balance issue, and should apply to both situations of equal and unequal sample sizes.

Accordingly, I just added an argument `pooled_sd` for the [`test_WEAT()`](https://psychbruce.github.io/PsychWordVec/reference/test_WEAT.html) function in my [`PsychWordVec`](https://psychbruce.github.io/PsychWordVec) package, which allows users to specify the choice between Caliskan's and the traditional approaches (though I strongly recommend Caliskan's as it provides a more conservative estimate).

By the way, I'm particularly curious about Caliskan and Lowe's correspondence that you mentioned. Could you possibly share with me their main opinions/explanations through my private email (baohws@foxmail.com)? I believe our discussion could be beneficial. Many thanks.
